name: Deploy

on:
    push:
        branches: [main, '*']
        # Only run for specific users
        if: |
            github.actor == 'fred4106' ||
            github.actor == 'kaqemeex' ||
            github.actor == 'typical-whack' ||
            github.actor == 'omniforce'
jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        environment:
            name: actions
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install dependencies
              run: npm install
            - name: Save Git SHA
              run: |
                  echo '{"gitSha": "${{ github.sha }}"}' > packages/ui/src/build-info.json
            - name: Prettier Check
              run: npm run prettier:check
            - name: Build
              run: npm run build
              env:
                  NODE_ENV: production
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}
                 publish_dir: ./packages/ui/dist
