name: Deploy

on:
    push:
        branches: 
         - main
permissions:
  contents: write
jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        environment:
            name: actions
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install dependencies
              run: npm install
            - name: Save Git SHA
              run: |
                  echo '{"gitSha": "${{ github.sha }}"}' > packages/ui/src/build-info.json
            - name: Prettier Check
              run: npm run prettier:check
            - name: Build
              run: npm run build
              env:
                  NODE_ENV: production

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: 'packages/ui/dist'
                ssh-key: ${{ secrets.DEPLOY_KEY }}
